spring.application.name=PRODUCT-SERVICE
server.port=8086

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/micro_product_db
spring.datasource.username=postgres
spring.datasource.password=akshay

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Logging
logging.level.com.micro.product_service=DEBUG

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true