spring.application.name=API-GATEWAY
server.port=${PORT:8070}

# Eureka Configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true



spring.cloud.gateway.routes[0].id=USER-SERVICE
spring.cloud.gateway.routes[0].uri=https://incredible-purpose-production-9cbe.up.railway.app
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**,/auth/**,/newsletter/**

spring.cloud.gateway.routes[1].id=PRODUCT-SERVICE
spring.cloud.gateway.routes[1].uri=https://jubilant-balance-production.up.railway.app
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**,/reviews/**,/uploads/**

spring.cloud.gateway.routes[2].id=ORDER-SERVICE
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[3].id=PAYMENT-SERVICE
spring.cloud.gateway.routes[3].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/payments/**

spring.cloud.gateway.routes[4].id=AI-ASSISTANT-SERVICE
spring.cloud.gateway.routes[4].uri=lb://AI-ASSISTANT-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/ai/**



# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true